### ISSUE TITLE
about create_images.py

### ISSUE THREAD

**Issue by ravikirandokka** [swethasubramanian/LungCancerDetection#15]
Hi Swetha,

Thank you very much for sharing this code. Could you please clarify the following below

    inpfile = mode + 'data'
    outDir = mode + '/image_'

In above 'data' is referring to??

**Comment by a56256324** [comment]
你好，解决了嘛？我也遇到了同样的问题

**Comment by ravikirandokka** [comment]
@a56256324 ..Can please let me know your comment in English translation..thanks

**Comment by a56256324** [comment]
Oh, I'm really sorry, my friend. I mean I want to generate some data of my own, but I also have some difficulties when I run create_images.py. Have you succeeded in debugging?
when i run python create_images.py train :
Traceback (most recent call last):
  File "create_images.py", line 179, in <module>
    main()
  File "create_images.py", line 176, in main
    Parallel(n_jobs =1 )(delayed(create_data)(idx, outDir, X_data) for idx in X_data.index)
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/arlab/.local/lib/python3.5/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "create_images.py", line 128, in create_data
    scan.save_image(outfile, width)
  File "create_images.py", line 114, in save_image
    image = self.get_subimage(width)
  File "create_images.py", line 93, in get_subimage
    self.read_mhd_image()
  File "create_images.py", line 65, in read_mhd_image
    self.ds = sitk.ReadImage(path[0])
IndexError: list index out of range
Did you run successfully through debugging? Or other mistakes have been solved. I hope to get your help. Thank you.

**Comment by arkdev9** [comment]
I am also getting the same error when trying to create my own data from raw files. @a56256324 Did you figure out what the problem is?

**Comment by arkdev9** [comment]
I figured out the reason that `create_images.py` wasn't properly working. It uses the pandas dataframe what was created with `do_test_train_split` to find all of the raw CT scans. The dataframe that was included in the git repo contains the dataframe that was generated by the repo owner. I don't have some of the scans that are in her dataframe and therefore it can't find the files. 

You can get around this issue by deleting all of the HDF5 datasets and pandas dataframes included in `src/data` and regenerating them from scratch using your own raw datasets. This means downloading the LUNA16 dataset or the LIDC which are massive. I suggest. you download a single scan from the [cancer imaging archive](https://www.cancerimagingarchive.net) and use that to test the prediction model. This also means modifying the `create_images.py` to preprocess the data with only a single scan. A `candidates.csv` is also needed for that single scan and the details you can copy from the place you downloaded the scan from.

**Comment by a56256324** [comment]
Thank you very much, my friend.
