### ISSUE TITLE
IndexError: list index out of range while training the model train.py

### ISSUE THREAD

**Issue by ganeshOnePlus** [swethasubramanian/LungCancerDetection#16]
Hi,
I tried to run train.py model directly from h5 dataset. During the model.fit, I get an IndexError: list index out of range. How can we solve this error? The error details is as:

model.fit(X_train_images, Y_train_labels, n_epoch = 1, shuffle=True,\
			validation_set = (X_val_images, Y_val_labels), show_metric = True,\
			batch_size = 5, snapshot_epoch = True, run_id = 'nodule3-classifier')
Traceback (most recent call last):

  File "<ipython-input-87-f5de8ee700bf>", line 1, in <module>
    model.fit(X_train_images, Y_train_labels, n_epoch = 1, shuffle=True,			validation_set = (X_val_images, Y_val_labels), show_metric = True,			batch_size = 5, snapshot_epoch = True, run_id = 'nodule3-classifier')

  File "C:\Users\Mahidol\Anaconda3\envs\Thesis\lib\site-packages\tflearn\models\dnn.py", line 184, in fit
    self.targets)

  File "C:\Users\Mahidol\Anaconda3\envs\Thesis\lib\site-packages\tflearn\utils.py", line 283, in feed_dict_builder
    feed_dict[net_inputs[i]] = x

IndexError: list index out of range

**Comment by SyedSaba** [comment]
Hello @swethasubramanian  can you please suggest how to solve the above error? Thanks in advance
